// lib/ui/generateWeightTicket.ts
//
// Renders a weight_records row to a shareable PNG "ticket" image via the
// Canvas API -- no PDF library, matches the app's existing copy/text/email
// share pattern but as an image (easier to text/AirDrop from a phone than
// a PDF, and the theme/fonts can't be controlled in a real print dialog
// anyway on most mobile browsers).

export type WeightTicketData = {
  recordedAt: string;
  equipmentLabel: string;
  heavyLbs: number;
  lightLbs: number;
  netLbs: number;
  plannerLbs: number | null;
  tareUpdated: boolean;
  priorTareLbs: number | null;
  notes: string | null;
};

const FONT = "Outfit, -apple-system, sans-serif";

function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    if (line && ctx.measureText(test).width > maxWidth) {
      lines.push(line);
      line = w;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function generateWeightTicketPng(data: WeightTicketData): Promise<Blob> {
  const W = 640;
  const PAD = 32;
  const contentW = W - PAD * 2;

  // Measure pass -- note text length determines final canvas height, which
  // has to be set before any drawing happens.
  const measure = document.createElement("canvas").getContext("2d")!;
  measure.font = `400 14px ${FONT}`;
  const noteLines = data.notes ? wrapText(measure, data.notes, contentW) : [];

  let h = 40 + 30 + 20 + (data.equipmentLabel ? 20 : 0) + 10 + 30; // header block
  h += 32 + 32 + 40; // heavy / light / net rows
  if (data.plannerLbs != null) h += 30;
  if (data.tareUpdated && data.priorTareLbs != null) h += 30;
  if (noteLines.length) h += 18 + noteLines.length * 20 + 6;
  h += 40; // footer

  const H = Math.max(420, Math.round(h));
  const DPR = 2;

  const canvas = document.createElement("canvas");
  canvas.width = W * DPR;
  canvas.height = H * DPR;
  const ctx = canvas.getContext("2d")!;
  ctx.scale(DPR, DPR);

  ctx.fillStyle = "#111111";
  ctx.fillRect(0, 0, W, H);

  let cy = 40;
  ctx.fillStyle = "#ffffff";
  ctx.font = `800 24px ${FONT}`;
  ctx.textAlign = "left";
  ctx.fillText("WEIGHT TICKET", PAD, cy);
  cy += 30;

  ctx.font = `600 14px ${FONT}`;
  ctx.fillStyle = "rgba(255,255,255,0.55)";
  ctx.fillText(
    new Date(data.recordedAt).toLocaleString(undefined, {
      month: "2-digit", day: "2-digit", year: "numeric", hour: "numeric", minute: "2-digit",
    }),
    PAD, cy
  );
  cy += 20;
  if (data.equipmentLabel) {
    ctx.fillText(data.equipmentLabel, PAD, cy);
    cy += 20;
  }

  cy += 10;
  ctx.strokeStyle = "rgba(255,255,255,0.15)";
  ctx.beginPath();
  ctx.moveTo(PAD, cy);
  ctx.lineTo(W - PAD, cy);
  ctx.stroke();
  cy += 30;

  function row(label: string, value: string, big: boolean) {
    ctx.textAlign = "left";
    ctx.font = `700 12px ${FONT}`;
    ctx.fillStyle = "rgba(255,255,255,0.4)";
    ctx.fillText(label.toUpperCase(), PAD, cy);
    ctx.textAlign = "right";
    ctx.font = big ? `800 22px ${FONT}` : `700 16px ${FONT}`;
    ctx.fillStyle = "#ffffff";
    ctx.fillText(value, W - PAD, cy);
    cy += big ? 40 : 32;
  }

  row("Heavy weight", `${Math.round(data.heavyLbs).toLocaleString()} lbs`, false);
  row("Light weight", `${Math.round(data.lightLbs).toLocaleString()} lbs`, false);
  row("Net weight", `${Math.round(data.netLbs).toLocaleString()} lbs`, true);

  ctx.textAlign = "left";

  if (data.plannerLbs != null) {
    const diff = Math.round(data.netLbs - data.plannerLbs);
    ctx.font = `600 13px ${FONT}`;
    ctx.fillStyle = diff === 0 ? "rgba(255,255,255,0.5)" : diff > 0 ? "#ef4444" : "#4ade80";
    ctx.fillText(
      `Planner: ${Math.round(data.plannerLbs).toLocaleString()} lbs  (${diff >= 0 ? "+" : ""}${diff})`,
      PAD, cy
    );
    cy += 30;
  }

  if (data.tareUpdated && data.priorTareLbs != null) {
    ctx.font = `600 13px ${FONT}`;
    ctx.fillStyle = "#fb923c";
    ctx.fillText(
      `Tare updated: ${Math.round(data.priorTareLbs).toLocaleString()} → ${Math.round(data.lightLbs).toLocaleString()} lbs`,
      PAD, cy
    );
    cy += 30;
  }

  if (noteLines.length) {
    cy += 6;
    ctx.font = `700 12px ${FONT}`;
    ctx.fillStyle = "rgba(255,255,255,0.4)";
    ctx.fillText("NOTES", PAD, cy);
    cy += 18;
    ctx.font = `400 14px ${FONT}`;
    ctx.fillStyle = "rgba(255,255,255,0.75)";
    for (const line of noteLines) {
      ctx.fillText(line, PAD, cy);
      cy += 20;
    }
  }

  ctx.font = `500 11px ${FONT}`;
  ctx.fillStyle = "rgba(255,255,255,0.25)";
  ctx.fillText("Generated by ProTankr", PAD, H - 20);

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error("Failed to render ticket image"))), "image/png");
  });
}

// Web Share API (with files) on mobile puts it straight into Messages/Mail/
// AirDrop's own share sheet; falls back to a plain download when unsupported
// or the user cancels the share sheet.
export async function shareOrDownloadTicket(blob: Blob, filename: string): Promise<void> {
  const file = new File([blob], filename, { type: "image/png" });
  const nav = navigator as Navigator & { canShare?: (data?: any) => boolean; share?: (data: any) => Promise<void> };

  if (nav.canShare && nav.share && nav.canShare({ files: [file] })) {
    try {
      await nav.share({ files: [file], title: filename });
      return;
    } catch {
      // User cancelled or share failed -- fall through to download.
    }
  }

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
