"use client";
// modals/ExpirationModal.tsx

import React, { useState } from "react";
import { FullscreenModal } from "@/lib/ui/FullscreenModal";
import type { ExpirationItem } from "../hooks/useExpirations";

type Props = {
  open: boolean;
  onClose: () => void;
  items: ExpirationItem[];
  // Navigate to the relevant modal on item tap
  onOpenEquipment: () => void;
  onOpenTerminals: () => void;
};

function buildReport(items: ExpirationItem[]): string {
  const date = new Date().toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" });
  const lines: string[] = [`ProTankr Expiration Report — ${date}`, ""];

  const trucks   = items.filter(i => i.entityType === "truck");
  const trailers = items.filter(i => i.entityType === "trailer");
  const terminals = items.filter(i => i.entityType === "terminal");

  const fmt = (i: ExpirationItem) => {
    const status = i.expired
      ? `EXPIRED ${Math.abs(i.daysLeft)}d ago`
      : `expires in ${i.daysLeft}d`;
    return `  ${i.expired ? "✕" : "⚠"} ${i.entityName} — ${i.label} (${status})`;
  };

  if (trucks.length > 0) {
    lines.push("TRUCK DOCUMENTS");
    trucks.forEach(i => lines.push(fmt(i)));
    lines.push("");
  }
  if (trailers.length > 0) {
    lines.push("TRAILER DOCUMENTS");
    trailers.forEach(i => lines.push(fmt(i)));
    lines.push("");
  }
  if (terminals.length > 0) {
    lines.push("TERMINAL CARDS");
    terminals.forEach(i => lines.push(fmt(i)));
    lines.push("");
  }

  lines.push("Generated by ProTankr");
  return lines.join("\n");
}

export default function ExpirationModal({ open, onClose, items, onOpenEquipment, onOpenTerminals }: Props) {
  const [copied, setCopied] = useState(false);
  const [shareError, setShareError] = useState("");

  const report = buildReport(items);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setShareError("Could not copy to clipboard.");
    }
  };

  const handleShare = async () => {
    setShareError("");
    if (navigator.share) {
      try {
        await navigator.share({ title: "ProTankr Expiration Report", text: report });
      } catch {}
    } else {
      // Fallback: mailto
      const subject = encodeURIComponent("ProTankr Expiration Report");
      const body = encodeURIComponent(report);
      window.open(`mailto:?subject=${subject}&body=${body}`);
    }
  };

  const trucks    = items.filter(i => i.entityType === "truck");
  const trailers  = items.filter(i => i.entityType === "trailer");
  const terminals = items.filter(i => i.entityType === "terminal");

  const rowStyle: React.CSSProperties = {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255,255,255,0.03)",
    cursor: "pointer",
  };

  const renderItem = (item: ExpirationItem, onTap: () => void) => {
    const isRed = item.expired;
    const statusColor = isRed ? "rgba(239,68,68,0.90)" : "rgba(234,179,8,0.90)";
    const statusText = item.expired
      ? `Expired ${Math.abs(item.daysLeft)}d ago`
      : `${item.daysLeft}d left`;

    return (
      <div
        key={item.id}
        role="button"
        tabIndex={0}
        onClick={onTap}
        onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onTap(); } }}
        style={rowStyle}
      >
        <div style={{ minWidth: 0, flex: 1 }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: "rgba(255,255,255,0.90)", marginBottom: 2 }}>
            {item.entityName}
          </div>
          <div style={{ fontSize: 11, color: "rgba(255,255,255,0.45)" }}>
            {item.label}
          </div>
        </div>
        <div style={{ fontSize: 12, fontWeight: 800, color: statusColor, whiteSpace: "nowrap" as const, flexShrink: 0 }}>
          {item.expired ? "⛔" : "⚠"} {statusText}
        </div>
      </div>
    );
  };

  const SectionHeader = ({ label }: { label: string }) => (
    <div style={{
      fontSize: 10, fontWeight: 800, letterSpacing: "0.1em",
      textTransform: "uppercase" as const,
      color: "rgba(255,255,255,0.30)",
      marginTop: 4, marginBottom: 6,
    }}>
      {label}
    </div>
  );

  const btnStyle: React.CSSProperties = {
    flex: 1,
    padding: "10px 0",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.05)",
    color: "rgba(255,255,255,0.80)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    letterSpacing: 0.2,
  };

  return (
    <FullscreenModal open={open} title="Expirations" onClose={onClose}>
      <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>

        {items.length === 0 ? (
          <div style={{ fontSize: 13, color: "rgba(255,255,255,0.45)" }}>
            Nothing expiring soon.
          </div>
        ) : (
          <>
            {/* Truck docs */}
            {trucks.length > 0 && (
              <div>
                <SectionHeader label="Truck Documents" />
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {trucks.map(item => renderItem(item, () => { onClose(); onOpenEquipment(); }))}
                </div>
              </div>
            )}

            {/* Trailer docs */}
            {trailers.length > 0 && (
              <div>
                <SectionHeader label="Trailer Documents" />
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {trailers.map(item => renderItem(item, () => { onClose(); onOpenEquipment(); }))}
                </div>
              </div>
            )}

            {/* Terminal cards */}
            {terminals.length > 0 && (
              <div>
                <SectionHeader label="Terminal Cards" />
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {terminals.map(item => renderItem(item, () => { onClose(); onOpenTerminals(); }))}
                </div>
              </div>
            )}

            {/* Share / Copy row */}
            <div style={{ borderTop: "1px solid rgba(255,255,255,0.07)", paddingTop: 14 }}>
              <div style={{ fontSize: 10, fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "rgba(255,255,255,0.30)", marginBottom: 8 }}>
                Share Report
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                <button type="button" onClick={handleCopy} style={btnStyle}>
                  {copied ? "✓ Copied" : "Copy"}
                </button>
                <button type="button" onClick={handleShare} style={btnStyle}>
                  Share / Email
                </button>
              </div>
              {shareError && (
                <div style={{ marginTop: 6, fontSize: 11, color: "rgba(239,68,68,0.80)" }}>{shareError}</div>
              )}
            </div>
          </>
        )}
      </div>
    </FullscreenModal>
  );
}
